### ISSUE TITLE
Org 9.7 org-element API incompatible changes

### ISSUE THREAD

**Issue by muntean-alex** [alphapapa/org-ql#364]
Good evening all,
I've had a small agenda-like org-ql setup that I used with org-mode for a while.
After not using it for a month or two, I've gotten back to using it and I've discovered that it throws an error.

"replace-regexp-in-string: Wrong type argument: stringp, [org-element-deferred org-element--headline-parse-title (nil) nil]"

```
(defun kr/agenda-next-month ()
  (interactive)
  (require 'org-ql)
(org-ql-search (org-agenda-files)
  '(and (or (deadline :to 30)
            (scheduled :to 30)
            (todo :to 30))
        (not (done))
        (not (tags "tag"))
        )
  :title "My next month"
  :super-groups '(
                  (:name "Today"
                         :scheduled today
                         :deadline today
                         :date today)
                  (:name "Due soon"
                         :scheduled future
                         :deadline auto)
                  (:name "Overdue"
                         :scheduled past
                         :deadline past)
                  (:name "Bills soon"
                         :tag "bills")
                  (:name "Due later"
                         :scheduled future
                         :deadline future)
                  (:name "Projects"
                         :tag "projects")
                  (:name "Misc"
                         :todo "TODO")
                  (:todo "READ"
                         :order 7)
                  (:todo "WAIT"
                         :order 6)
                  (:priority "A" :order 1)
                  (:priority "B" :order 2)
                  (:priority "C" :order 3)))
)
```

Anybody facing something similar?
Any hints on tracking down this issue?

Thank you kindly!

**Comment by muntean-alex** [comment]
Hello!
I've nuked the straight directory and rebuilt with `doom upgrade`
Sadly, no cigar.
Gives me the same error.

**Comment by yantar92** [comment]
Hmm. Then, may you do `M-x debug-on-error` and post the full backtrace?

**Comment by muntean-alex** [comment]
```
Debugger entered--Lisp error: (wrong-type-argument stringp [org-element-deferred org-element--headline-parse-title (nil) nil])
  string-match("\\[\\[\\(\\(?:[^][\\]\\|\\\\\\(?:\\\\\\\\\\)*[][]\\|\\\\+[^][]\\)+\\)..." [org-element-deferred org-element--headline-parse-title (nil) nil] 0)
  replace-regexp-in-string("\\[\\[\\(\\(?:[^][\\]\\|\\\\\\(?:\\\\\\\\\\)*[][]\\|\\\\+[^][]\\)+\\)..." #f(compiled-function (m) #<bytecode -0x8ce38b99175cad3>) [org-element-deferred org-element--headline-parse-title (nil) nil] nil t)
  org-link-display-format([org-element-deferred org-element--headline-parse-title (nil) nil])
  org-ql-view--format-element((headline (:standard-properties [667 707 679 707 0 667 (:title) nil nil 681 705 nil nil 1 nil [org-element-deferred org-element--headline-deferred nil t] nil #<buffer inbox.org>] :pre-blank 0 :raw-value [org-element-deferred org-element--headline-parse-title (nil) nil] :title [org-element-deferred org-element--headline-parse-title (nil) nil] :level [org-element-deferred org-element--headline-parse-title (nil) nil] :priority [org-element-deferred org-element--headline-parse-title (nil) nil] :tags [org-element-deferred org-element--headline-parse-title (nil) nil] :todo-keyword [org-element-deferred org-element--headline-parse-title (nil) nil] :todo-type [org-element-deferred org-element--headline-parse-title (nil) nil] :footnote-section-p [org-element-deferred org-element--headline-parse-title (nil) nil] :archivedp [org-element-deferred org-element--headline-parse-title (nil) nil] :commentedp [org-element-deferred org-element--headline-parse-title (nil) nil] :org-marker #<marker in no buffer> :org-hd-marker #<marker in no buffer>)))
  mapcar(org-ql-view--format-element ((headline ...) (headline ...) (headline ...) (headline ...) (headline ...) (headline ...) (headline ...) (headline ...) (headline ...) (headline ...) (headline ...) (headline ...) (headline ...) (headline ...) (headline ...) (headline ...) (headline ...) (headline ...) (headline ...) (headline ...) ...))
  -map(org-ql-view--format-element ((headline ...) (headline ...) (headline ...) (headline ...) (headline ...) (headline ...) (headline ...) (headline ...) (headline ...) (headline ...) (headline ...) (headline ...) (headline ...) (headline ...) (headline ...) (headline ...) (headline ...) (headline ...) (headline ...) (headline ...) ...))
  org-ql-search(("[[myfiles.org]]") (and (or (deadline :to 30) (scheduled :to 30) (todo :to 30)) (not (done)) (not (tags "tag"))) :title "My Agenda View" :super-groups ((:name "Today" :scheduled today :deadline today :date today) (:name "Due soon" :scheduled future :deadline auto) (:name "Overdue" :scheduled past :deadline past) (:name "Bills soon" :tag "bills") (:name "Due later" :scheduled future :deadline future) (:name "Projects" :tag "projects") (:name "Misc" :todo "TODO") (:todo "READ" :order 7) (:todo "WAIT" :order 6) (:priority "A" :order 1) (:priority "B" :order 2) (:priority "C" :order 3)))
  kr/agenda-next-month()
  funcall-interactively(kr/agenda-next-month)
  call-interactively(kr/agenda-next-month nil nil)
  command-execute(kr/agenda-next-month)
```

**Comment by yantar92** [comment]
I see now. This is because `org-ql-view--format-element` relies on internal org-element representation, which has been changed in the cutting edge Org. 

@alphapapa Please check out https://git.savannah.gnu.org/cgit/emacs/org-mode.git/tree/etc/ORG-NEWS#n40

**Comment by yantar92** [comment]
@muntean-alex Meanwhile, you may need to downgrade Org mode. https://github.com/org-roam/org-roam/issues/2361 has a lot of instructions how to do it.

**Comment by alphapapa** [comment]
> I see now. This is because `org-ql-view--format-element` relies on internal org-element representation, which has been changed in the cutting edge Org.
> 
> @alphapapa Please check out https://git.savannah.gnu.org/cgit/emacs/org-mode.git/tree/etc/ORG-NEWS#n40

ISTM that this change, while it may be an improvement in several ways, is going to break a LOT of third-party packages, like this one.  The org-element sexp representation has been unchanged for many years and versions.  I feel like there should be a transitional period with the new representation under a different API to preserve compatibility with other code in the wild.

I mean, thinking of all the places in org-ql and org-super-agenda that will likely have to be changed for this, and have multiple code paths by Org version, for YEARS to come, because of this change...  the various org-ql predicates and org-super-agenda group selectors... It makes me want to import the old org-element API and just use that instead.

On top of that, there is no guidance for developers to adapt their code to the new API, no helper functions or macros...?  This is looking like many, many hours of work and hundreds or thousands of lines of extra code to work with multiple Org versions and APIs, and that cluttering up the packages' source code for years until the old Org versions are truly not used anymore.

>  Version 9.7 (not released yet)

Ok, so, please, please, PLEASE, do not release Org 9.7 with this change as-is.  There has got to be some kind of compatibility layer for downstream libraries.  This burden can't just be dumped on downstream developers and users.

**Comment by yantar92** [comment]
Adam Porter ***@***.***> writes:

> ISTM that this change, while it may be an improvement in several ways,
> is going to break a LOT of third-party packages, like this one.  The
> org-element sexp representation has been unchanged for many years and
> versions.  I feel like there should be a transitional period with the
> new representation under a different API to preserve compatibility
> with other code in the wild.

Only the packages that were abusing the internal representation
_instead_ of using the (previously) existing API may be broken.
Except a single (rare) case when packages had a need to traverse all
properties in an element - this case had no proper API previously.

> I mean, thinking of all the places in org-ql and org-super-agenda that
> will likely have to be changed for this, and have multiple code paths
> by Org version, for YEARS to come, because of this change... the
> various org-ql predicates and org-super-agenda group selectors... It
> makes me want to import the old org-element API and just use that
> instead.

The change is not as breaking. And I do not recall where in org-ql sexp
representation is used.

> On top of that, there is no guidance for developers to adapt their
> code to the new API, no helper functions or macros...?

Please refer to https://git.savannah.gnu.org/cgit/emacs/org-mode.git/tree/etc/ORG-NEWS#n59

-- 
Ihor Radchenko // yantar92,
Org mode contributor,
Learn more about Org mode at <https://orgmode.org/>.
Support Org development at <https://liberapay.com/org-mode>,
or support my work at <https://liberapay.com/yantar92>

**Comment by muntean-alex** [comment]
> @muntean-alex Meanwhile, you may need to downgrade Org mode. [org-roam/org-roam#2361](https://github.com/org-roam/org-roam/issues/2361) has a lot of instructions how to do it.

For reference, this worked for me and fixed the issue.
Thank you very much!

**Comment by maikol-solis** [comment]
I had the same issue, and I thought that it was something to do with `org-ql-block`. I reported the problem here https://github.com/alphapapa/org-ql/issues/38#issuecomment-1705110039.

However, downgrading `org` to `9.6`, solved completely the problem. In doom, I added this line into my `packages.el`:

```
(package! org :pin "806abc5a2bbcb5f884467a0145547221ba09eb59")
```

Best.

**Comment by alphapapa** [comment]
Thanks to all for reporting.  Please try the commit I just pushed on the `wip/364` branch and let me know if that works on Org 9.7.

**Comment by gdindi** [comment]
Hi,
I have tried to replace org-ql-viel.el with the version in the `wip/364` branch and I keep getting this error:

`(void-function org-ql-view--resolve-element-properties)`

I have byte-compiled and native-compiled (I am using native-comp). I am doing something wrong but I don't see it.

What is the recommended way of testing this? My org-ql is installed with `package-install` and I am using "20230908.722".

Thanks.

**Comment by alphapapa** [comment]
@gdindi You shouldn't try to mix and match files from different commits.  You should follow the instructions in the readme to install with Quelpa, adding this to the recipe form: `:branch "wip/364"`.

**Comment by gdindi** [comment]
Makes sense. Thanks. I unistalled org-ql with `package-delete` and installed with this in my init.el:

```
(quelpa
 '(org-ql 
           :fetcher github
           :repo "alphapapa/org-ql"
           :branch "wip/364"
           :files (:defaults (:exclude "helm-org-ql.el"))))
(require 'org-ql)
```

The package is installed in `~/.emacs.d/elpa/org-ql-20230904.214910`. I restarted Emacs, but I still get this backtrace:

```
(void-function org-ql-view--resolve-element-properties)
org-ql-view--resolve-element-properties((headline (:standard-properties [699314 699314 699346 699691 699691 0 (:title) nil nil nil nil 699348 699691 2 #<buffer biblio.org> [org-element-deferred org-element--headline-deferred nil t] nil nil] :pre-blank 0 :raw-value [org-element-deferred org-element--headline-parse-title (nil) nil] :title [org-element-deferred org-element--headline-parse-title (nil) nil] :level [org-element-deferred org-element--headline-parse-title (nil) nil] :priority [org-element-deferred org-element--headline-parse-title (nil) nil] :tags [org-element-deferred org-element--headline-parse-title (nil) nil] :todo-keyword [org-element-deferred org-element--headline-parse-title (nil) nil] :todo-type [org-element-deferred org-element--headline-parse-title (nil) nil] :footnote-section-p [org-element-deferred org-element--headline-parse-title (nil) nil] :archivedp [org-element-deferred org-element--headline-parse-title (nil) nil] :commentedp [org-element-deferred org-element--headline-parse-title (nil) nil] :org-marker #<marker at 699314 in biblio.org> :org-hd-marker #<marker at 699314 in biblio.org>)))
org-ql-view--format-element((headline (:standard-properties [699314 699314 699346 699691 699691 0 (:title) nil nil nil nil 699348 699691 2 #<buffer biblio.org> [org-element-deferred org-element--headline-deferred nil t] nil nil] :pre-blank 0 :raw-value [org-element-deferred org-element--headline-parse-title (nil) nil] :title [org-element-deferred org-element--headline-parse-title (nil) nil] :level [org-element-deferred org-element--headline-parse-title (nil) nil] :priority [org-element-deferred org-element--headline-parse-title (nil) nil] :tags [org-element-deferred org-element--headline-parse-title (nil) nil] :todo-keyword [org-element-deferred org-element--headline-parse-title (nil) nil] :todo-type [org-element-deferred org-element--headline-parse-title (nil) nil] :footnote-section-p [org-element-deferred org-element--headline-parse-title (nil) nil] :archivedp [org-element-deferred org-element--headline-parse-title (nil) nil] :commentedp [org-element-deferred org-element--headline-parse-title (nil) nil] :org-marker #<marker at 699314 in biblio.org> :org-hd-marker #<marker at 699314 in biblio.org>)))
```

I don’t understand the void function message, since the code contains the `defalias`, but I don’t understand how `defalias` works wrt `defun`.

I may be introducing more noise than help in this issue. I just wanted to test seing that the OP had found another solution and that nobody seemed to have tested your fix.

If I can be of any help, do not hesitate to tell me what to do, but I don’t want to pollute the issue if the problem comes from my config.

Thanks.

**Comment by alphapapa** [comment]
@gdindi Thanks for testing that.  I think I made a mistake, wrapping the `defalias` call in `eval-and-compile` (a "thinko," I think).  I just pushed to that branch again.  Please try again and let me know if it works.  (You may find it useful to use [this command](https://github.com/alphapapa/unpackaged.el#upgrade-a-quelpa-use-package-forms-package) to easily upgrade the Quelpa-installed package.)

**Comment by gdindi** [comment]
Hi. I just tried and keep getting the same error.

**Comment by alphapapa** [comment]
> Hi. I just tried and keep getting the same error.

Did you delete other versions of org-ql and restart Emacs before testing?

**Comment by gdindi** [comment]
On Tue 12-Sep-2023 at 16:16:15 +02, Adam Porter
***@***.***> wrote: 
>  Hi. I just tried and keep getting the same error.
>
> Did you delete other versions of org-ql and restart Emacs before testing?
>

Yes. I also deleted the git clone in .emacs.d/quelpa to make sure quelpa
was getting the most recent sources.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.
>

--

**Comment by alphapapa** [comment]
@gdindi My apologies, I made another silly mistake.  I just pushed another commit to that branch, and I've confirmed that it works on Org 9.6.  Please let me know if it works for you.

**Comment by gdindi** [comment]
On Tue 12-Sep-2023 at 19:07:12 +02, Adam Porter
***@***.***> wrote: 
> @gdindi My apologies, I made another silly mistake. I just pushed another
> commit to that branch, and I've confirmed that it works on Org 9.6. Please
> let me know if it works for you.

Thanks for the quick reaction. Now the defalias works, but there is a
new error:

```
Debugger entered--Lisp error: (error "‘org-element-at-point’ cannot be used in non-Org b...")
  signal(error ("‘org-element-at-point’ cannot be used in non-Org b..."))
  error("`org-element-at-point' cannot be used in non-Org b..." #<buffer  *temp*> fundamental-mode)
  org-element-at-point(nil)
  org--property-local-values("STYLE" nil nil)
  org-entry-get(nil "STYLE" selective)
  org-is-habit-p()
org-ql-view--format-element((headline (:standard-properties [699314 699314 699346 699691 699691 0 (:title) nil nil nil nil 699374 699689 2 #<buffer biblio.org> nil nil nil] :pre-blank 0 :raw-value [org-element-deferred org-element--headline-raw-value (8 31) nil] :title #("Read doc" 0 23 (face org-scheduled)) :level 2 :priority nil :tags nil :todo-keyword #("NEXT" 0 4 (face (:background "red" :weight bold))) :todo-type todo :footnote-section-p [org-element-deferred org-element--headline-footnote-section-p nil nil] :archivedp [org-element-deferred org-element--headline-archivedp nil nil] :commentedp nil :org-marker #<marker at 699314 in biblio.org> :org-hd-marker #<marker at 699314 in biblio.org> :scheduled (timestamp (:standard-properties [699357 nil nil nil 699373 0 nil nil nil nil nil nil nil nil nil nil nil nil] :type active :range-type nil :raw-value "<2023-09-14 Thu>" :year-start 2023 :month-start 9 :day-start 14 :hour-start nil :minute-start nil :year-end 2023 :month-end 9 :day-end 14 :hour-end nil :minute-end nil)) :relative-due-date #("in 2d" 0 5 (help-echo "<2023-09-14 Thu>")))))
```

I suppose that the temp buffer has to be in org mode before formatting?

>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.
>

--

**Comment by alphapapa** [comment]
> I suppose that the temp buffer has to be in org mode before formatting?

I don't know what that temp buffer is from.  The code in question is here:

https://github.com/alphapapa/org-ql/blob/1bd7bb4af6382b00d199d9cd843fadd7e764fa82/org-ql-view.el#L895-L897

`org-is-habit-p` is called with point at `(org-element-property :begin element)` using `org-with-point-at`, so it should be called in the `org-mode` buffer the entry comes from.

> I am using org 9.7-pre

It may or may not matter here, but in general, if you're using a pre-release version, that version number isn't sufficient, because it covers anything from Org 9.6 to Org 9.7, so you should specify which commit you're using.

Anyway, I wonder if the value of `(org-element-property :begin element)` is not what is expected even after calling `(org-element-properties-resolve node 'force-undefer)`.  @yantar92 Do you happen to know off the top of your head if that is the case?

**Comment by alphapapa** [comment]
Looking more closely at the backtrace, the element seems to have no `:begin` property at all.  It looks like the value might be in the `:standard-properties` vector as an integer position rather than as a marker.

But I also see what appear to be some still-deferred properties, which I don't understand, because we should be forcing them to resolve here:

https://github.com/alphapapa/org-ql/blob/1bd7bb4af6382b00d199d9cd843fadd7e764fa82/org-ql-view.el#L821-L833

Maybe the problem is that the `:begin` property was always an integer, so `org-is-habit-p` was always being called in the wrong buffer, and the error is just being revealed by `org-element-at-point` being changed to signal an error when it's not called in an `org-mode` buffer now.

Please try the commit I just pushed which changes it to use the heading marker instead.

**Comment by gdindi** [comment]
I will pretend I understand your explanation ;)

Good news: it works at least with my custom searches that I use most frequently. I will keep on testing in case I find other issues.

Thanks!

**Comment by yantar92** [comment]
Adam Porter ***@***.***> writes:

> Anyway, I wonder if the value of `(org-element-property :begin element)` is not what is expected even after calling `(org-element-properties-resolve node 'force-undefer)`.  @yantar92 Do you happen to know off the top of your head if that is the case?

org-element does not store markers (storing markers slows down editing).
So, it is expected that :begin property is a number, not a marker.

-- 
Ihor Radchenko // yantar92,
Org mode contributor,
Learn more about Org mode at <https://orgmode.org/>.
Support Org development at <https://liberapay.com/org-mode>,
or support my work at <https://liberapay.com/yantar92>

**Comment by yantar92** [comment]
Adam Porter ***@***.***> writes:

> But I also see what appear to be some still-deferred properties, which I don't understand, because we should be forcing them to resolve here:
>
> https://github.com/alphapapa/org-ql/blob/1bd7bb4af6382b00d199d9cd843fadd7e764fa82/org-ql-view.el#L821-L833

`org-element-properties-resolve' should resolve everything if it is
actually called.

> Maybe the problem is that the `:begin` property was always an integer, so `org-is-habit-p` was always being called in the wrong buffer, and the error is just being revealed by `org-element-at-point` being changed to signal an error when it's not called in an `org-mode` buffer now.

Most likely.

> Please try the commit I just pushed which changes it to use the heading marker instead.

FYI, in Org 9.7, `org-with-point-at' can take ELEMENT as an argument and
it will then set the buffer correctly, according to new :buffer ELEMENT
property. Not the case in earlier Org versions though.

-- 
Ihor Radchenko // yantar92,
Org mode contributor,
Learn more about Org mode at <https://orgmode.org/>.
Support Org development at <https://liberapay.com/org-mode>,
or support my work at <https://liberapay.com/yantar92>

**Comment by alphapapa** [comment]
@yantar92 Thanks.  (And apologies for the ping; I realized afterward that I didn't need to bother you about this, but it was too late.)

**Comment by alphapapa** [comment]
@gdindi Thanks.  I'll target this change for v0.8 of org-ql, since it's not a fix per se, and since Org 9.7 is yet to be released.  Please do let me know if you find any problems.

**Comment by alphapapa** [comment]
I'll go ahead and make this change in v0.7.3.  Hopefully this is the only fix that needs to be applied.

**Comment by alphapapa** [comment]
I've pushed these fixes to master under v0.8-pre.  I hope they resolve this issue, but I'll leave it open for a while in case more problems are found.

To all: Please test and let me know if the problem is resolved for you.  Thanks.

**Comment by kunalomizer** [comment]
I just upgraded and it appears to be working now. The org-ql query does execute and display the results as expected.   Thank you! 
Although I do still see the error in *Messages* : Error running timer ‘org-reveal’: (error "‘org-element-at-point’ cannot be used in non-Org buffer #<buffer *Org QL View: MWTasks*> (org-agenda-mode)") [19 times]

**Comment by alphapapa** [comment]
@kunalomizer Thanks.  I don't know what's going on with that error from a timer.  `org-reveal` is called from this hook:

https://github.com/alphapapa/org-ql/blob/ca23b1c7bda7adbad994637de2ce8e862193e30d/org-ql-find.el#L42

But that's not called from a timer:

https://github.com/alphapapa/org-ql/blob/ca23b1c7bda7adbad994637de2ce8e862193e30d/org-ql-find.el#L89

And I don't know what would be calling `org-element-at-point` in the `org-ql-view` buffer.

**Comment by treitmaier** [comment]
The error was also raised as an org-roam issue here: https://github.com/org-roam/org-roam/issues/2391

**Comment by alphapapa** [comment]
AFAICT this is fixed.  Please file a new issue if it happens again after I tag v0.8.

**Comment by TristanCacqueray** [comment]
@alphapapa not sure if that is expected, but the entries returned by `org-ql-select` (Version: 20240905.2358) may still contain deferred values. In my case I was reformatting them like this:

```elisp
(defun one/format (item)
  (let* ((properties (cadr item))
         (title (plist-get properties :raw-value))
         (scheduled (plist-get properties :scheduled))
         (ts (format-time-string "%FT%T%z" (org-timestamp-to-time scheduled))))
    (format "%s %s" ts (or/remove-links title))))
```

This was broken by `s-trim: Wrong type argument: stringp, [org-element-deferred org-element--headline-parse-title (nil) t]`, and I needed this tweak to fix the bug:

```diff
-(defun one/format (item)
-  (let* ((properties (cadr item))
+(defun one/format (node)
+  (let* ((item (org-element-properties-resolve node 'force-undefer))
+         (properties (cadr item))
```

**Comment by alphapapa** [comment]
@TristanCacqueray The commit that resolves this issue, https://github.com/alphapapa/org-ql/commit/8250349e35709c3ab1c4372d6790d9665559c7dd, resolves the deferred node properties in the function `org-ql-view--format-element`, which is used in `org-ql-view` views.  If you are directly calling `org-ql-select` and handling the `org-element` nodes yourself, you will need to handle property resolution yourself.  It would not be appropriate for `org-ql-select` to do so automatically, because in some cases it could be unnecessary, which would cause an unnecessary performance hit.
